# Uncomment the next line to define a global platform for your project

platform :osx, '10.13'

target 'ncm-peeler' do
  use_frameworks!
  pod 'CryptoSwift'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'ID3TagEditor', '~> 2.0'
end
