# Uncomment the next line to define a global platform for your project

platform :osx, '10.13’

target 'ncm-peeler' do
  use_frameworks!
  pod 'SwiftyJSON'
  pod 'ID3TagEditor'
  pod 'CryptoSwift'
end
